[package]
name = "gsm-windows-audio-capture"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
winapi = { version = "0.3.9", features = [
    "audioclient",
    "audiosessiontypes",
    "combaseapi",
    "handleapi",
    "mmdeviceapi",
    "objbase",
    "propidl",
    "synchapi",
    "unknwnbase",
    "winbase",
] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
