[pytest]
testpaths = tests
python_files = test_*.py
addopts = -p no:cacheprovider -p no:tmpdir
filterwarnings =
    ignore:Using `@model_validator` with mode='after' on a classmethod is deprecated.*:pydantic.warnings.PydanticDeprecatedSince212:google\.genai\.types
