// SPDX-License-Identifier: GPL-3.0-or-later

// Every `hd_*` runtime message type in one list: the requests and events the
// extension sends or answers, and the reply types its code spells out (any
// other reply is named after its request's type plus `_result`). Nothing loads
// this file at run time: each call site still writes its own type, and
// test/message-types.test.mjs keeps this list equal to the names they write.
// It is a classic script, like reader-options.js, so a content script can load
// it and a module can import it for its side effect.
(function () {
  "use strict";

  const MESSAGE_TYPES = [
    "hd_anki_audio",
    "hd_anki_browse",
    "hd_anki_discover",
    "hd_anki_document",
    "hd_anki_fields",
    "hd_anki_index_refresh",
    "hd_anki_maturity",
    "hd_anki_preflight",
    "hd_anki_preflight_batch",
    "hd_anki_screenshot",
    "hd_anki_screenshot_discard",
    "hd_anki_setup",
    "hd_anki_status",
    "hd_anki_submit",
    "hd_anki_view",
    "hd_anki_word_status",
    "hd_anki_word_status_changed",
    // The Hachidori Relay add-on's API requests, answered by api-host.js, which
    // passes the hd_api_dictionary_* dictionary downloads on to the engine.
    "hd_api_anki_card_formats",
    "hd_api_anki_fields",
    "hd_api_dictionaries",
    "hd_api_dictionary_close",
    "hd_api_dictionary_open",
    "hd_api_dictionary_read",
    "hd_api_kanji_entries",
    "hd_api_term_entries",
    "hd_api_tokenize",
    "hd_api_version",
    "hd_apply_state",
    "hd_audio_candidates",
    "hd_audio_play",
    "hd_audio_playing",
    "hd_audio_stop",
    "hd_audio_test",
    "hd_audio_voices",
    "hd_audio_voices_changed",
    "hd_backup_auto_cleanup",
    "hd_backup_auto_get",
    "hd_backup_auto_list",
    "hd_backup_auto_prepare",
    "hd_backup_auto_roots",
    "hd_backup_base_read",
    "hd_backup_cancel",
    "hd_backup_cas",
    "hd_backup_download",
    "hd_backup_export",
    "hd_backup_prepare",
    "hd_backup_read",
    "hd_backup_release",
    "hd_backup_restore",
    "hd_custom_append",
    "hd_custom_cas",
    "hd_custom_read",
    "hd_custom_save",
    "hd_debug_log",
    "hd_debug_log_result",
    "hd_engine_config",
    "hd_engine_config_result",
    "hd_import",
    "hd_import_abort",
    "hd_import_begin",
    "hd_import_chunk",
    "hd_import_commit",
    "hd_import_commit_result",
    "hd_kanji",
    "hd_lookup",
    "hd_lookup_dictionary",
    "hd_lookup_stats_cleanup",
    "hd_lookup_stats_read",
    "hd_lookup_stats_record",
    "hd_lookup_stats_reset",
    "hd_media",
    "hd_media_result",
    "hd_memory",
    "hd_memory_total",
    "hd_memory_total_result",
    "hd_netflix_capture_cancel",
    "hd_netflix_capture_finish",
    "hd_netflix_capture_start",
    "hd_netflix_line_audio",
    "hd_netflix_load",
    "hd_open_external",
    "hd_options_write",
    "hd_options_write_result",
    "hd_page_zoom",
    "hd_reader_command",
    "hd_reload",
    "hd_remove",
    "hd_segment",
    "hd_setup_anki",
    "hd_setup_cas",
    "hd_setup_install",
    "hd_setup_progress",
    "hd_setup_record",
    "hd_sharing_client_link",
    "hd_sharing_client_probe",
    "hd_sharing_client_unlink",
    "hd_sharing_host_disable",
    "hd_sharing_host_enable",
    "hd_sharing_status",
    "hd_state_cas",
    "hd_state_read",
    "hd_status",
    "hd_status_result",
    "hd_styles",
    // Stands in for a message's missing type in its failure reply
    // (`hd_unknown_result`) and its debug log entry.
    "hd_unknown",
    "hd_updates_check",
    "hd_updates_install",
    "hd_updates_schedule",
    "hd_upload_append",
    "hd_upload_discard",
    "hd_upload_identity",
    "hd_upload_import",
    "hd_upload_reset",
    "hd_word_status_override",
  ];

  globalThis.HDMessageTypes = { MESSAGE_TYPES };
}());
